### ISSUE TITLE
Refactoring/Extending DownloadManager

### ISSUE THREAD

**Issue by HereThereBeDragons** [cvmfs/cvmfs#3095]
Here a first overview of the changes we talked about:

**Refactoring**
- Move all the componentes in a new directory cvmfs/network/

- Make struct Counters in download.h a subclass of DownloadManager

- JobInfo
    - Becomes a class
    - Has 3 sections: Input parameters, Statusinfo, Output parameters

- Download sink
    - Independent of the exact download destination, all should inherit from sink.h
    - JobInfo should then only have a single parameter "destinationSink"

- Create a Pipe Class
    - Extremly light-weight (maybe just typedefs?, or some template that takes an enum?)
    - Goal: Better understand which pipe communicates with which classes

    
- Replace Init/Fini functions of DownloadManager with Create/Destructor to comfort latest coding style

- Create classes for 
    - HostInfo
    - HostList
    - ProxyList
    - ProxyGroups

    - Must support the following functionalities:
        - Add/Remove

**New features**
- Add health check for proxies and? hosts (see #2945 )
- Add CVMFS_DOWNLOAD_INFINITE_RETRY client parameter and allow for infinite retries for downloading, iterating through proxies/hosts even if they fail until one is back up online ( see #2944 )

**Comment by HereThereBeDragons** [comment]
First couple of Tasks:

- [x] Move files into newly created `network` folder
- [x] JobInfo: should then only have a single parameter "destinationSink"
- [x] Template pipe class in `posix.h`
- [x] Document pipe class for developers
- [x] Replacement of `Init()/Fini()` by constructor + `Create()`

**Comment by HereThereBeDragons** [comment]
health check: allow to define a health check URL either 1) one url for all proxy groups or 2) one url per proxy group

**Comment by HereThereBeDragons** [comment]
next steps:

- [x] Replace `Fini()` with destructor
- [ ] replace placeholder for custome proxy health check and sharding policy with proper version (#2945 , #2944)
    - see PRs #3121
- [ ] replace `jobinfo` with `jobcontext` (#3217)
- [ ] add zstd compression algorithm (#3141)
- [ ] maybe also: Add CVMFS_DOWNLOAD_INFINITE_RETRY client parameter and allow for infinite retries for downloading, iterating through proxies/hosts even if they fail until one is back up online ( #2944 )

**Comment by HereThereBeDragons** [comment]
- [ ] For debug messages: link jobinfo object and curl requests #3492

**Comment by HereThereBeDragons** [comment]
- [ ] Parallelize decompression of download requests (#3493)

**Comment by HereThereBeDragons** [comment]
- [x] better logging in download manager ( https://github.com/cvmfs/cvmfs/pull/3573 , part of 2.11.3)
- [ ] add hostname to logging within `UpdateProxiesUnlocked`
