### ISSUE TITLE
ZSTD in CVMFS

### ISSUE THREAD

**Issue by jblomer** [cvmfs/cvmfs#3141]
It would be nice to use the zstd in cvmfs, rather than the older zlib.  This issue should collect what needs to be done for adding zstd support in cvmfs. Note that the storage format hashes files after compression. Unless we extend the naming scheme, the file name itself unfortunately does not indicate the compression algorithm or settings.

Build system
==========

- [ ] Add cmake module to find zstd.  Possibly vendor a version of zstd. It depends on how stable the algorithm is. We need to be able to recompress a file and get the same bits

Infrastructure code
==============

- [ ] Add zstd compressor
- [ ] Refactor decompression: we should have a `Decompressor` class akin to the compressor

Server
=====

- [ ] Nested catalog: either add a flags field or add a suffix to the sha1 text field to indicate the compression of the catalog
- [ ] Manifest: add a new key that indicates the compression algorithm of the root file catalog

Client
====

- [ ] Find a way for `cvmfs_fsck` to verify a cache with differently compressed files. Perhaps try all algorithms. Perhaps extend the file naming scheme. We could also add a header or footer in the files in the cache itself to store the compression settings.
- [ ] In the download manager, `CallbackCurlData`: add support for multiple compression algorithms

**Comment by mharvey-jt** [comment]
#3149  to vendor zstd and add cmake setup

**Comment by HereThereBeDragons** [comment]
#3149 PR (for proper linking issue + PR)

**Comment by HereThereBeDragons** [comment]
Here is a more detailed action plan. No big changes of the ideas proposed in the first post. 

## Current Situation
- Catalogs are always `zlib` compressed 
- Files are either `zlib`-compressed or uncompressed
- For Files the compression setting is a 3-bit option (= 8 options)

## Introducing `zstd`
- Catalog and Files should support following compression formats: `none`,  `zlib`, `zstd-fast`, `zstd-normal`, `zstd-extrem`
- Each publish command should be able to set the compression option. Files and catalogs should have different options

### Steps

1)
- [ ] Define zstd bits in catalog flag field ( #3582 )
- [ ] Add compression settings to nested catalog table ( #3583 )
- [ ] Add compression settings to manifest (of the root catalog) ( #3584 )

2)
- [ ] Move compression into separate directory ( #3584 )
- [ ] Split existing compression into separate files for each algorithm; refactor to only have one compression method per algorithm and take abstract in/out buffers ( #3589 )
- [ ] Add abstract decompressor (complimentary to the compressor) for `zlib`, `echo` ( #3603 )
- [ ] Change namespace from `zlib` to `compression`/`zip` (suggested by jakob)
- [ ] JobInfo needs to keep track of compression info?

3)
- [ ] Add zstd compressor/decompressor
- [ ]  Vendor zstd --> use #3149

Other things to do
- [ ] Client: cvmfs_fsck checks the (uncompressed) cache -->  try out all compression settings to find fitting match before failing
- [ ] Server: Add compression options to publisher (independent settings for catalogs and files)

**Comment by DrDaveD** [comment]
@jblomer had a good idea during discussion about this today: for graceful failures on older clients, a small zlib root catalog could be created that only has a README that explains that the client is too old.  I think this makes more sense than having all catalogs still zlib compressed.  I think even better would be to call the file something like CLIENT_TOO_OLD.  The .cvmfspublished manifest would then of course need a new field for the zstd root catalog hash, not only a field saying which algorithm is used.

**Comment by HereThereBeDragons** [comment]
i think this would only make sense if the catalogs are all zstd compressed. 

if we have mixed repos with zlib catalogs, i dont believe this is a wise choice. some warning would be nice - but full denial of the zlib files i dont think it a good choice

**Comment by DrDaveD** [comment]
Yes, it is my expectation that on the WLCG we will want all of the new catalogs to use zstd compression once we switch.    My expectation is that we will not want to support a transition period where both types of files are generated, because it will both slow down publication and use extra space.  Once we turn the switch on a repository to start using zstd, I think it should completely fail for old clients in a predictable way such as this, forcing the client to upgrade if that repository is still needed.  To have it only fail for new files would just be confusing.

Perhaps there would be another option where someone wants to generate both types of files for a while.  Then yes, you wouldn't use a mostly blank zlib catalog like this.  I do not expect to use this option on the WLCG however.  I don't know who would want that.

I also don't expect to immediately replace all old catalogs and data once a repository is converted to start using zstd.  So the new client should be able to handle starting with a zstd root catalog but switching to zlib anywhere along the way, for old catalogs.  I guess in order to avoid calculating the zlib hash during publication, de-duplication will no longer work between files created when in zlib mode and when in zstd mode.  That's unfortunate, but I don't see a good way around it.  There probably should be a conversion process for all the old catalog and data files that we can run later just like we can with eliminate-bulk-hashes.

**Comment by vvolkl** [comment]
I'll close the linked PRs, as it's unlikely I can review and merge them in the short term, before other urgent  items from the plan of work are finished. That doesn't mean that Zstd is off the agenda; I've collected all of Laura's branches under `zstd/<branchname>` so they won't be lost, and we'll revisit zstd from there.
